project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  title: "Rachel Thomas, PhD"
  site-url: https://rachel.fast.ai
  description: "AI, science, education, & ethics"
  image: "/images/thomas-card.jpg"
  open-graph:
    description: "AI, science, education, & ethics"
  twitter-card:
    creator: "@math_rachel"
    site: "@math_rachel"
    description: "AI, science, education, & ethics"
  margin-header: subscribe.html
  body-footer: "<br><br><i>I look forward to reading your responses. Create a free GitHub account to comment below.</i>"
  comments:
    giscus:
        repo: racheltho/rachel-blog
        repo-id: "R_kgDOIxf7pQ"
        category: "Announcements"
        category-id: "DIC_kwDOIxf7pc4CcEZ1"
        mapping: "pathname"
        reactions-enabled: true
        input-position: "bottom"
        theme: "light"
       
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: twitter
        href: https://twitter.com/math_rachel
      - icon: linkedin
        href: https://www.linkedin.com/in/rachel-thomas-942a7923/
      - icon: youtube
        href: https://www.youtube.com/playlist?list=PLtmWHNX-gukLQlMvtRJ19s7-8MrnRV6h6
      - icon: rss
        href: index.xml
      - text: Archive
        href: archive.qmd  
format:
  html:
    theme: flatly
    linkcolor: "#168873"
    css: styles.css



